
on:
  push:
    branches:
    - main
    - release/*
  pull_request:
    branches:
    - main

jobs:
  update_flake:
    name: deploy to staging
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v5
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - name: Update Nix Flake Lock
        uses: DeterminateSystems/update-flake-lock@v21
      - name: Build Nix package
        run: nix build
          
