
on:
  push:
    branches:
    - main
    - release/*
  pull_request:
    branches:
    - main

jobs:
  update_flake:
    name: deploy to staging
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v5
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - name: Build Nix package
        run: nix build
          
      - name: Auto Versioning
        uses: Soumeh-zz/Auto-Versioning@v2.0
      - name: Auto Release
        uses: CupOfTea696/gh-action-auto-release@v1.0.2
          
