on:
  push:
    branches:
    - main
    - release/*

jobs:
  update_flake:
    name: deploy to staging
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v5
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - name: Auto Release
        run: |
          cd ./src/
          NAME=$(echo "${{ github.repository }}" | cut -d "/" -f 1)
          tar -czvf ${NAME}.tar.gz *
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ github.token }}"
          automatic_release_tag: "latest"
          prerelease: false
          files: |
            ${NAME}.tar.gz
