on:
  push:
    branches:
    - main
    - release/*
    - setup-auto-release

jobs:
  update_flake:
    name: update and check flake.lock
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4

      - name: Update Nix Flake Lock
        if: ${{ github.event_name != 'pull_request' }}
        uses: DeterminateSystems/update-flake-lock@v21

      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v5

  auto_ralease:
    name: deploy to staging
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Generate tar.gz from src
        id: generate_tar
        run: |
          cd ./src/
          FILE_NAME="$(basename "${{ github.repository }}").tar.gz"
          echo "FILE_NAME=$FILE_NAME" >> $GITHUB_ENV
          tar -czvf ${FILE_NAME} *

      - name: Generate Release version from date
        id: date
        run: |
          TAG_NAME="build-$(date +'%Y%m%d-%H%M%S')"
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
          echo "Tag name will be: $TAG_NAME"

      - name: Create Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ github.token }}"
          automatic_release_tag: ${{ env.TAG_NAME }}
          prerelease: false
          files: |
            ./src/${{ env.FILE_NAME }}
